-------- BCP OBJECT SECTION ------
--zapytanie pokazujace rodzaje OBJC_CLASS w ZOBJECTS
--2TYPES
use DB_NAME; \
SELECT DISTINCT OBJC_CLASS, count(*) \
  FROM ZOBJECTS \
 WHERE OBJC_CLASS like '%AAAA_PAR%' \
   AND (SITUATION_DATE = (SELECT MAX(SITUATION_DATE) \
                         FROM BSDATE) \
        OR SITUATION_DATE = '00000000') \
 GROUP BY OBJC_CLASS; 

-------- IFRS9 SECTIION
--Wyswietla liste kontraktow i facility dla danego Facility
--2IFRSFCL
use DB_NAME; \
SELECT SOURCE_CONTRACT_REF, CONTRACT_ID, sp.DESCRIPTION PROD_TYPE,f.DESCRIPTION FCL_TYPE, CURRENCY_CODE as CCY, \
       PRINCIPAL, FACILITY_LIMIT_AMOUNT FCL_LIMIT, REMAINING_LIMIT_AMOUNT REMAINING, ORIGIN_DATE ORIGIN, MATURITY_DATE MATURITY \
  FROM CONTRACT c LEFT OUTER JOIN FACILITY_TYPE f on c.FACILITY_TYPE = f.FACILITY_TYPE_ENUM \
   LEFT OUTER JOIN SPECIFIC_PRODUCT sp ON c.SPECIFIC_PRODUCT_ENUM=sp.SPECIFIC_PRODUCT_ENUM \
 WHERE ('BBBB_PAR'='' AND SITUATION_DATE = (select max(SITUATION_DATE) from BSDATE) \
       OR SITUATION_DATE = 'BBBB_PAR') \
  and  (SOURCE_CONTRACT_REF = 'AAAA_PAR' \
      or FACILITY_REF = 'AAAA_PAR') \
 ORDER BY FACILITY_REF; 


--Wyswietla liste facility na ostatni SD, like %NAZWA%  
--2IFRSLISTFCL
use DB_NAME; \
SELECT SOURCE_CONTRACT_REF \
  FROM CONTRACT \
 WHERE FACILITY_TYPE is not null \
   AND ('BBBB_PAR'='' AND SITUATION_DATE = (select max(SITUATION_DATE) from BSDATE) \
       OR SITUATION_DATE = 'BBBB_PAR') \
   AND SOURCE_CONTRACT_REF like '%AAAA_PAR%' ;


