-------- LCR REPORT SECTION
--wyswietla jakie zostaly utworzone raporty na dana SD i dla pewnych REPORT_NAME
--LCR_R1
use DB_NAME; \
select DISTINCT REPORT_NAME, PORTFOLIO_NAME, SCENARIO_NAME, BASEL_REPORTING_FRAMEWORK_ENUM \
  from LCR_REPORTS \
 WHERE ('AAAA_PAR' = '' AND SITUATION_DATE = (select max(SITUATION_DATE) from BSDATE) \
        OR SITUATION_DATE = 'AAAA_PAR') \
   AND REPORT_NAME like '%BBBB_PAR%' \
 ORDER BY REPORT_NAME, PORTFOLIO_NAME, SCENARIO_NAME, BASEL_REPORTING_FRAMEWORK_ENUM;

--wyswietla jakie zostaly utworzone audyty na dana SD i dla pewnych REPORT_NAME
--LCR_A1
use DB_NAME; \
select DISTINCT REPORT_NAME, PORTFOLIO_NAME, SCENARIO_NAME, BASEL_REPORTING_FRAMEWORK_ENUM \
  from LCR_REPORTS_AUDIT \
 WHERE ('AAAA_PAR' = '' AND SITUATION_DATE = (select max(SITUATION_DATE) from BSDATE) \
        OR SITUATION_DATE = 'AAAA_PAR') \
   AND REPORT_NAME like '%BBBB_PAR%' \
 ORDER BY REPORT_NAME, PORTFOLIO_NAME, SCENARIO_NAME, BASEL_REPORTING_FRAMEWORK_ENUM;

--wyswietla ROW_ID w audycie na dana SD dla REPORT_NAME i dla pewnych BASEL_ENUM   
--LCR_A2
use DB_NAME; \
select PORTFOLIO_NAME, SCENARIO_NAME, BASEL_REPORTING_FRAMEWORK_ENUM, ROW_ID \
  from LCR_REPORTS_AUDIT \
 WHERE ('AAAA_PAR' = '' AND SITUATION_DATE = (select max(SITUATION_DATE) from BSDATE) \
        OR SITUATION_DATE = 'AAAA_PAR') \
   AND REPORT_NAME = 'BBBB_PAR' \
   AND BASEL_REPORTING_FRAMEWORK_ENUM like '%CCCC_PAR%' \
 ORDER BY REPORT_NAME, PORTFOLIO_NAME, SCENARIO_NAME, BASEL_REPORTING_FRAMEWORK_ENUM;

--wyswietla w jakich wierszach uwzgledniany jest dany CONTRACT_ID:  SD REPORT_NAME CONTRACT_ID
--LCR_A3
use DB_NAME; \
select PORTFOLIO_NAME, SCENARIO_NAME, BASEL_REPORTING_FRAMEWORK_ENUM, ROW_ID, CONTRACT_ID \
  from LCR_REPORTS_AUDIT \
 WHERE ('AAAA_PAR' = '' AND SITUATION_DATE = (select max(SITUATION_DATE) from BSDATE) \
        OR SITUATION_DATE = 'AAAA_PAR') \
  AND REPORT_NAME = 'BBBB_PAR' \
  AND CONTRACT_ID = 'CCCC_PAR' \
 ORDER BY PORTFOLIO_NAME, SCENARIO_NAME, BASEL_REPORTING_FRAMEWORK_ENUM, ROW_ID;



