SELECT CONCAT('SELECT "',t.TABLE_NAME,'" TABNAME, SITUATION_DATE,COUNT(*) FROM ',t.TABLE_NAME,' GROUP BY SITUATION_DATE UNION ALL')
FROM INFORMATION_SCHEMA.TABLES t,INFORMATION_SCHEMA.COLUMNS c
WHERE t.TABLE_TYPE = 'BASE TABLE' AND t.TABLE_CATALOG='AAAA'
and t.TABLE_NAME=c.TABLE_NAME
and t.TABLE_CATALOG=c.TABLE_CATALOG
and c.COLUMN_NAME='SITUATION_DATE'
order by t.TABLE_NAME

